### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wanderer** [primea/js-primea-hypervisor#114]
- [x] move ports
  - [x] get instance by path
  - [x] signal when moved
      - [x] update non-entryport channels
- [x] send ports in message
- [x] copy ports 
- [ ] port introspection
  - [x] get type (message / contract / storage)
  - [ ] get value
  - [ ] get id
- [x] iterate ports
  - [x] order map 
- [ ] id introspection
 - [ ] get parent
 - [x] get nonce
